name: SGPvP
version: ${project.version}
main: com.sgpvp.main
api-version: 1.16
authors: [FinneganMcGuire, vscala]
description: SGPvP Plugin
website: sgpvp.com
commands:
  timewizard:
    description: Gives Clock, Clock can stop timearound you stoping all players from moving!
  werewolf:
    description: Become A Wolf!
  brawler:
    description: Punch with fist, your stronger
  chameleon:
    description: Turn into animals
  lumberjack:
    description: Cut Trees Faster
  grandpa:
    description: Old man stick hits enemies far
  turtle:
    description: Holding shift makes you stronger
  milkman:
    description: Milk gives you buffs
  fireman:
    description: Gives water bucket and fire resistance
  beastmaster:
    description: Instant Wolf Tameing
  pyromancer:
    description: Fire stuff
  recycler:
    description: Recycler bowls after souping
  glider:
    description: fly
  groundhog:
    description: groundhog
  cultivator:
    description: seed place = grow fast!
  sunwalker:
    description: Buffs during the day
  blacksmith:
    description: Upgrade your items
  viper:
    description: Chance to apply poision
  snail:
    description: Chance to apply slow
  Stomper:
    description: Stomp on enemies damaging them
  Switcher:
    description: Switch places with another entity
  Chemist:
    description: Start the game with potions
  Phantom:
    description: Fly for brief periods of time
  game:
    description: commands to modify the current game
